Implement azure vault provider
EladLeev/kubeseal-convert pull request #14
Opened 2022-12-13 17:00 UTC by kroonprins

For #3

2022-12-14 11:05 UTC, EladLeev requested changes

2022-12-14 11:05 UTC, EladLeev commented on pkg/kubeseal-convert/handlers/azurekeyvault/azurekeyvault.go
> +		mp[secretName] = *secret.Value
No need to fill out the map - I used `map[string]interface{}` as I don't have a concrete struct for the returning secret.
Later on, I'm using the secret data in order to build a k8s secret and pass it to `kubeseal` command:
[buildDataBytes](https://github.com/EladLeev/kubeseal-convert/blob/main/pkg/kubeseal-convert/handlers/kubesealconvert/secret.go#L11)

This is how we end up using all the secret KV content

2022-12-14 11:05 UTC, EladLeev commented on README.md
> +:white_check_mark: Azure Key Vault
```suggestion
:white_check_mark: Azure Key Vault  - contributed by @kroonprins
```

2022-12-14 11:05 UTC, EladLeev commented on README.md
> +:white_check_mark: Azure Key Vault
I want to praise the contributors! 🤩

2022-12-14 11:06 UTC, EladLeev commented
Thank you so much @kroonprins 🤩 
I added a few comments, can you please address them before merging?

2022-12-14 14:02 UTC, kroonprins commented
@EladLeev , new version pushed (I will squash the commits once all comments resolved).
For the first 2 comments, I changed the implementation for retrieving the secrets. My approach was a bit wrong there I think, because the terminology in aws/hashicorp is a bit different than in azure key vault (a 'secretName' in azure key vault is just one secret value, not a collection of secrets).
I also made one small extra adaption to change the command name to 'akv' (instead of 'az') as AKV seems to be an abbreviaion they use from time to time in the microsoft docs so seems more suitable.

2022-12-16 22:10 UTC, EladLeev commented
LGTM.
Thank you for that 🙏

2022-12-16 22:10 UTC, merged